#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

mount | grep -q ' on /media/disk type ' || exit 1

sudo mkdir -p /media/disk/sysbackup || exit 1

DoItEasy sudo rsync \
    -zva \
    --delete \
    --delete-excluded \
    --exclude '/mnt*' \
    --exclude '/media*' \
    --exclude '/proc*' \
    --exclude '/sys*' \
    --exclude '/dev*' \
    --exclude '/tmp*' \
    / /media/disk/sysbackup/

