#!/bin/sh

printf 'passphrase? '
read PASSPHRASE
export PASSPHRASE

export AWS_ACCESS_KEY_ID=`cat $HOME/text/s3-access-key-id`        
export AWS_SECRET_ACCESS_KEY=`cat $HOME/text/s3-secret-access-key`  
BUCKET=`cat $HOME/text/s3-bucket-name`

normal_excludes="$HOME/.mozilla/*/*/Cache/*
**/*.dll
**/core.*
**/*.pyc
**/*.pyo
**/*.o
$HOME/.wine/drive_c/windows/temp
$HOME/.thumbnails
$HOME/.covers
$HOME/.macromedia
$HOME/.gqview/thumbnails/**
$HOME/.gaim/icons/*
$HOME/.local/share/Last.fm/cache/*
$HOME/.cache
$HOME/.mozilla/firefox/7cbgnodf.default/Cache
$HOME/.config/chromium/Default/Cache
$HOME/.enna/covers
$HOME/.enna/thumbnails
$HOME/.thumbnails
$HOME/.java
$HOME/.adobe
$HOME/.macromedia"

normal_excludes_file=`mktemp`
echo "$normal_excludes" > "$normal_excludes_file"

all_excludes="$normal_excludes
$HOME/Music
$HOME/ripped
$HOME/.VirtualBox/HardDisks
$HOME/cyclo"

all_excludes_file=`mktemp`
echo "$all_excludes" > "$all_excludes_file"

backup() {
    from="$1"
    to="$2"
    excludes_file="$3"
    volsize="$4"
    cutoff=`date -d 'now - 6 months' +'%Y-%m-%d'`
    verbosity="-v5"

    echo; echo "cutoff is: $cutoff"; echo

    set -x
    duplicity cleanup "$verbosity" --force "$to"

    duplicity --asynchronous-upload "$verbosity" "$from" "$to" \
        --full-if-older-than "$cutoff" --volsize "$volsize" \
        --exclude-other-filesystems \
        --scp-command "scp -l 400" \
        --exclude-globbing-filelist="$excludes_file"

    duplicity remove-older-than "$cutoff" "$verbosity" --force "$to"

    duplicity collection-status "$verbosity" "$to"
    set +x
}

backup "$HOME" file://$HOME/nasty/Backups/nick/home-duplicity "$normal_excludes_file" 10
backup "$HOME" s3+http://"$BUCKET" "$all_excludes_file" 3
