#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

if ! mount | grep -q ' on /media/seagate-ext type '
then
    echo "seagate-ext is not mounted."
    exit 1
fi

sudo mkdir -p /media/seagate-ext/sysbackup || exit 1

sudo nice -n20 ionice -c3 rsync \
    -Pzva \
    --delete \
    --delete-excluded \
    --exclude "$HOME/nasty" \
    --exclude "$HOME/.gvfs" \
    --exclude "$HOME/big/transmission" \
    --exclude "$HOME/.Trash*" \
    --exclude "$HOME/big/.Trash*" \
    --exclude "$HOME/.cache" \
    --exclude "*.swap" \
    --exclude '/mnt*' \
    --exclude '/media*' \
    --exclude '/proc*' \
    --exclude '/sys*' \
    --exclude '/dev*' \
    --exclude '/tmp*' \
    / /media/seagate-ext/sysbackup/

