#!/bin/zsh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# DoItEasy: run a command with the lowest cpu and i/o priorities.  requires
# sudo-ing to root to get the lowest i/o priority, but drops privileges to run
# the command

# see also: TakeItEasy

# due to inadequate word quoting behavior of bash, zsh is required for the
# arguments to be properly passed through

sudo nice -n 20 ionice -c3 sudo -u $USER $@

