#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# FlacToMP3: recursively find all .flac files in the current directory and
# convert them to mp3, changing .flac to .mp3 in the new files' filenames and
# leaving the original files intact.

find . -name "*.flac" | while read filename
do
    mp3_filename=`basename "$filename" ".flac"`.mp3
    flac -dc "$filename" | lame --preset standard - "$mp3_filename"
done

