#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# M4AToMP3: recursively find all .m4a files in the current directory and
# convert them to mp3, changing .m4a to .mp3 in the new files' filenames and
# leaving the original files intact.

mkfifo tmp.pipe
find . -name "*.m4a" | while read filename
do
    mp3_filename=`basename "$filename" ".m4a"`.mp3
    mplayer -noconsolecontrols -ao pcm:file=tmp.pipe "$filename" &
    lame --preset standard tmp.pipe "$mp3_filename"
done
rm -f tmp.pipe

