#!/bin/sh

gconftool-2 --type string --set /apps/metacity/general/theme                    "nothing"
gconftool-2 --type string --set /apps/metacity/general/mouse_button_modifier    "<Alt>"
gconftool-2 --type string --set /apps/metacity/general/focus_mode               mouse
gconftool-2 --type bool   --set /apps/metacity/general/raise_on_click           false
gconftool-2 --type int    --set /apps/metacity/general/num_workspaces           9
gconftool-2 --type bool   --set /apps/metacity/general/compositing_manager      true
gconftool-2 --type bool   --set /apps/metacity/general/resize_with_right_button true

gconftool-2 --type string --set /apps/metacity/window_keybindings/toggle_maximized "<Super>f"
gconftool-2 --type string --set /apps/metacity/window_keybindings/close            "<Ctrl><Alt>w"

gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_1 "<Ctrl><Alt>u"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_2 "<Ctrl><Alt>i"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_3 "<Ctrl><Alt>o"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_4 "<Ctrl><Alt>j"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_5 "<Ctrl><Alt>k"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_6 "<Ctrl><Alt>l"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_7 "<Ctrl><Alt>m"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_8 "<Ctrl><Alt>comma"
gconftool-2 --type string --set /apps/metacity/global_keybindings/switch_to_workspace_9 "<Ctrl><Alt>period"

gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_1 "<Ctrl><Alt>x"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_2 "<Super>z"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_3 "<Super>x"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_4 "<Super>c"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_5 "<Super>v"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_6 "<Super>b"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_7 "<Super>h"
gconftool-2 --type string --set /apps/metacity/global_keybindings/run_command_8 "<Super>l"

gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_1 "$HOME/sw/bin/urxvt"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_2 "$HOME/dev/bin/mpris-remote prev"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_3 "$HOME/dev/bin/mpris-remote stop"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_4 "$HOME/dev/bin/mpris-remote play"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_5 "$HOME/dev/bin/mpris-remote pause"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_6 "$HOME/dev/bin/mpris-remote next"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_7 "wmctrl -r :ACTIVE: -e 0,0,0,1024,1152"
gconftool-2 --type string --set /apps/metacity/keybinding_commands/command_8 "wmctrl -r :ACTIVE: -e 0,1024,0,1024,1152"

# no desktop icons
gconftool-2 --type bool   --set /apps/nautilus/preferences/show_desktop false

# fast key repeat
gconftool-2 --type int    --set /desktop/gnome/peripherals/keyboard/delay 220
gconftool-2 --type int    --set /desktop/gnome/peripherals/keyboard/rate  90

# don't lock the screen
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock_on_suspend                  false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock_on_hibernate                false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock_on_blank_screen             false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock_on_use_screensaver_settings false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock/gnome_keyring_hibernate     false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock/gnome_keyring_suspend       false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock/hibernate                   false
gconftool-2 --type bool   --set /apps/gnome-power-manager/lock/suspend                     false
