#!/bin/sh

setting()
{
    gconftool-2 --type $2 --set /apps/metacity/$1 "$3"
}

setting general/theme                    string "nothing"
setting general/mouse_button_modifier    string "<Alt>"
setting general/focus_mode               string mouse
setting general/raise_on_click           bool   false
setting general/num_workspaces           int    9
setting general/compositing_manager      bool   true
setting general/resize_with_right_button bool   true

setting window_keybindings/toggle_maximized string "<Super>f"
setting window_keybindings/close            string "<Ctrl><Alt>w"

setting global_keybindings/switch_to_workspace_1 string "<Ctrl><Alt>u"
setting global_keybindings/switch_to_workspace_2 string "<Ctrl><Alt>i"
setting global_keybindings/switch_to_workspace_3 string "<Ctrl><Alt>o"
setting global_keybindings/switch_to_workspace_4 string "<Ctrl><Alt>j"
setting global_keybindings/switch_to_workspace_5 string "<Ctrl><Alt>k"
setting global_keybindings/switch_to_workspace_6 string "<Ctrl><Alt>l"
setting global_keybindings/switch_to_workspace_7 string "<Ctrl><Alt>m"
setting global_keybindings/switch_to_workspace_8 string "<Ctrl><Alt>comma"
setting global_keybindings/switch_to_workspace_9 string "<Ctrl><Alt>period"

setting global_keybindings/run_command_1 string "<Ctrl><Alt>x"
setting global_keybindings/run_command_2 string "<Super>z"
setting global_keybindings/run_command_3 string "<Super>x"
setting global_keybindings/run_command_4 string "<Super>c"
setting global_keybindings/run_command_5 string "<Super>v"
setting global_keybindings/run_command_6 string "<Super>b"
setting global_keybindings/run_command_7 string "<Super>h"
setting global_keybindings/run_command_8 string "<Super>l"

setting keybinding_commands/command_1 string "/home/death/sw/bin/urxvt"
setting keybinding_commands/command_2 string "/home/death/dev/bin/mpris-remote prev"
setting keybinding_commands/command_3 string "/home/death/dev/bin/mpris-remote stop"
setting keybinding_commands/command_4 string "/home/death/dev/bin/mpris-remote play"
setting keybinding_commands/command_5 string "/home/death/dev/bin/mpris-remote pause"
setting keybinding_commands/command_6 string "/home/death/dev/bin/mpris-remote next"
setting keybinding_commands/command_7 string "wmctrl -r :ACTIVE: -e 0,0,0,1024,1152"
setting keybinding_commands/command_8 string "wmctrl -r :ACTIVE: -e 0,1024,0,1024,1152"



