#!/bin/sh

printf 'passphrase? '
read PASSPHRASE
export PASSPHRASE

export AWS_ACCESS_KEY_ID=`cat $HOME/text/s3-access-key-id`        
export AWS_SECRET_ACCESS_KEY=`cat $HOME/text/s3-secret-access-key`  
BUCKET=`cat $HOME/text/s3-bucket-name`

for dir in cleanups dev images irclogs Maildir other phonepics pics scripts sw text
do
    duplicity cleanup --asynchronous-upload --allow-source-mismatch -v5 --force      s3+http://"$BUCKET"/"$dir"
    duplicity         --asynchronous-upload --allow-source-mismatch -v5 "$HOME/$dir" s3+http://"$BUCKET"/"$dir" \
        --gpg-options='--compress-algo=bzip2 --bzip2-compress-level=9'
done

duplicity cleanup --asynchronous-upload --allow-source-mismatch -v5 --force s3+http://"$BUCKET"/dotfiles
duplicity         --asynchronous-upload --allow-source-mismatch -v5 "$HOME" s3+http://"$BUCKET"/dotfiles \
    --gpg-options='--compress-algo=bzip2 --bzip2-compress-level=9' \
    --exclude "$HOME/.mozilla/*/*/Cache/*" \
    --exclude "**/*.dll" \
    --exclude "**/core.*" \
    --exclude "**/*.pyc" \
    --exclude "**/*.pyo" \
    --exclude "**/*.o" \
    --exclude "$HOME/.wine/drive_c/windows/temp" \
    --exclude "$HOME/.thumbnails" \
    --exclude "$HOME/.covers" \
    --exclude "$HOME/.macromedia" \
    --exclude "$HOME/.gqview/thumbnails/**" \
    --exclude "$HOME/.gaim/icons/*" \
    --exclude "$HOME/.local/share/Last.fm/cache/*" \
    --exclude "$HOME/." \
    --exclude "$HOME/.." \
    --include "$HOME/.*" \
    --exclude "**"
