#!/usr/bin/env python

import os, sys, subprocess, stat

proc = subprocess.Popen(['dpkg', '-L', sys.argv[1]], stdout=subprocess.PIPE)
stdout, stderr = proc.communicate()

total = 0

for filename in filter(None, stdout.split('\n')):
    try:
        st = os.stat(filename)
    except OSError: # broken symlink
        continue

    if stat.S_ISREG(st[stat.ST_MODE]) and not stat.S_ISLNK(st[stat.ST_MODE]):
        total += st[stat.ST_SIZE]

print total
