#!/bin/sh

MountPhone
num=`find /media/phone/mobile/picture/ -name '*.jpg' | wc -l`
if [ "$num" != 0 ]
then
    mv -v /media/phone/mobile/picture/*.jpg ~/phonepics/
else
    echo "no pics"
fi
Umount /media/phone
