#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

set -x

azureus_pid=`ps auxww | grep -i azureus | grep java | awk '{print $2}'`

test -n "$azureus_pid" && kill $azureus_pid
sleep 1
rempd stop
Umount /mnt
aumix -v 0
sudo s2disk # go to sleep

# ...

# wake up

# for some reason mplayer does something magic that brings the sound back
# device when it sometimes breaks after a suspend
an_mp3=`find $HOME/music -type f -name '*.mp3' | head -n1`
mplayer -noconsolecontrols "$an_mp3" >/dev/null 2>&1 &

while ! ps auxww | grep "$an_mp3" | grep -q mplayer
do sleep 0.3; done

kill `ps auxww | grep "$an_mp3" | grep mplayer | awk '{print $2}'`
sleep 1
aumix -v 80

# need external disk re-mounted first
MountSeagate >/dev/null 2>&1

rempd start

