#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

set -x

Umount /mnt &
aumix -v 0 &

wait

sudo s2disk # go to sleep

# ...

# wake up

( # sound
    # for some reason mplayer does something magic that brings the sound back
    # device when it sometimes breaks after a suspend
    an_mp3=`find $HOME/Music -type f -name '*.mp3' | head -n1`
    mplayer -noconsolecontrols "$an_mp3" >/dev/null 2>&1 &

    while ! ps auxww | grep "$an_mp3" | grep -q mplayer
    do sleep 0.3; done

    kill `ps auxww | grep "$an_mp3" | grep mplayer | awk '{print $2}'`
    aumix -v 80
    echo "sound done"
) &

( # video
    sudo vbetool vbemode set 3
    sleep 1
    FixX
    echo "video done"
) &

(
    echo "mounting seagate"
    MountSeagate >/dev/null 2>&1
    echo "done mounting seagate"
) &

wait

