#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# USAGE: startx [:display]

DISPLAY=:0
test -z "$1" || DISPLAY=$1
export DISPLAY

if test -z "$DBUS_SESSION_BUS_ADDRESS"
then
    eval `dbus-launch --sh-syntax --exit-with-session`
    export DBUS_SESSION_BUS_ADDRESS
    export DBUS_SESSION_BUS_PID
fi

ERRORLOG="$HOME/.my-x-errors-$DISPLAY"

X -noreset "$DISPLAY" > "$ERRORLOG" 2>&1 &

# try a bunch of times until X is there
for try in `seq 10`
do
    if xdpyinfo >/dev/null 2>&1
    then
        exec >> "$ERRORLOG" 2>&1
        sh $HOME/scripts/xstartup.sh
        exit 0
    else
        sleep 0.5
    fi
done

echo "Couldn't connect to display $DISPLAY."
exit 1

