#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# USAGE: startx [:display]

DISPLAY=:0
test -z "$1" || DISPLAY=$1
export DISPLAY

ERRORLOG="$HOME/.my-x-errors-$DISPLAY"

X -br -noreset "$DISPLAY" > "$ERRORLOG" 2>&1 &

# try a bunch of times until X is there
for try in `seq 10`
do
    if xdpyinfo >/dev/null 2>&1
    then
        exec >> "$ERRORLOG" 2>&1
        xstartup.sh
        exit 0
    else
        sleep 0.5
    fi
done

echo "Couldn't connect to display $DISPLAY."
exit 1

