#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

set -x
mkdir -p "$HOME/tmp/music"
chmod -R 755 "$HOME/tmp/music"
rename 'y/A-Z/a-z/' "$HOME"/tmp/music/*
ls -1 "$HOME/tmp/music" | while read artist
do
    artistdir="$HOME/tmp/music/$artist"

    rename 'y/A-Z/a-z/' "$artistdir"/*

    find "$artistdir" -type f -iname '*.mp3' | while read i
    do
        chmod 644 "$i"
        rename 'y/A-Z/a-z/' "$i"
    done

    find "$artistdir" -type f -not -name '*.mp3' |
        while read i
        do
            echo "delete $i"
            rm -f "$i"
        done

    if [ "$1" = "-i" ]
    then
        find "$artistdir" -mindepth 1 -maxdepth 1 -type d | while read albumdir
        do
            echo "incomplete -> YES"
            touch "$albumdir"/incomplete
        done
    fi

    mkdir -p "$HOME/music/$artist"
    find "$artistdir" -type d -mindepth 1 -maxdepth 1 |
        while read albumdir
        do
            mv "$albumdir" "$HOME/music/$artist/"
            album=`basename "$albumdir"`
            python $HOME/dev/bin/Id3 "$HOME/music/$artist/$album"
        done
    rmdir "$artistdir"
done

