#!/bin/zsh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

set -x

music="$HOME/tmp/music"
finished="$HOME/music"

mkdir -p "$music"

find "$music" \
    -not -iname '*.mp3' \
    -not -iname incomplete \
    -type f \
    -exec rm -f {} \; || exit 1
for i in "$music"/*; do rename 'y/A-Z/a-z/' "$i"; done
for i in "$music"/*/*; do rename 'y/A-Z/a-z/' "$i"; done
for i in "$music"/*/*/*; do rename 'y/A-Z/a-z/' "$i"; done

for artistdir in "$music"/*
do
    artist=`basename "$artistdir"`
    for albumdir in "$music/$artist"/*
    do
        album=`basename "$albumdir"`

        test "$1" = "-i" && touch "$albumdir"/incomplete

        dest="$finished/$artist/$album"
        if [ -e "$dest" -a ! rmdir "$dest" 2>/dev/null ]
        then
            if [ `ls "$dest"` = 'incomplete' ]
            then
                rm "$dest"/incomplete || exit 1
                rmdir "$dest" || exit 1
            else
                echo "$dest already exists!"
                # this exit only exits the loop (not the entire script) if
                # running under bash/dash..wtf?
                exit 1
            fi
        fi

        mkdir -p "`dirname \"$dest\"`"
        mv -v "$albumdir" "$dest"
    done
    rmdir "$artistdir"
done

Id3 "$finished" || exit 1

