#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# TranscodeToMP3: recursively find all files in the current directory with the
# specified extension (the only argument) and convert them to mp3, using
# mplayer to decode them, changing the extension to .mp3 in the new files'
# filenames and leaving the original files intact.

extension="$1"

masterlist=`tempfile`
part1=`tempfile`
part2=`tempfile`

find . -name "*$extension" | sort > "$masterlist"

numfiles=`wc -l < "$masterlist"`

head -n$(($numfiles / 2                )) "$masterlist" > "$part1"
tail -n$(($numfiles / 2 + $numfiles % 2)) "$masterlist" > "$part2"

transcode_files ()
{
    while read filename
    do
        mkfifo "$filename".pipe
        mp3_filename=`basename "$filename" "$extension"`.mp3
        echo "$filename -> $mp3_filename"
        DoItEasy mplayer -really-quiet -noconsolecontrols -ao pcm:file="$filename".pipe "$filename" 2>/dev/null &
        DoItEasy lame --quiet --preset extreme "$filename".pipe "$mp3_filename"
        rm -f "$filename".pipe
    done
}

transcode_files < "$part1" &
transcode_files < "$part2"

wait

