#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# Umount: sometimes disks get mounted multiple times on accident.  this makes
# sure they are umount-ed as many times as necessary to make them go away.

while sudo umount "$1" >dev/null 2>&1; do :; done

