#!/bin/sh

# Written by Nick Welch <nick@incise.org>.  Author disclaims copyright.

# WAVToMP3: recursively find all .wav files in the current directory and
# convert them to mp3, changing .wav to .mp3 in the new files' filenames and
# leaving the original files intact.

find . -name "*.wav" | while read filename
do
    mp3_filename=`basename "$filename" ".wav"`.mp3
    lame --preset standard "$filename" "$mp3_filename"
done

